#MADE BY TG = @SOHAILKHAN_ANIME | GITHUB NOOBSOHAIL 
#FAIRY TAIL QUOTES
ANIMEQUOTES=(
"The mistakes people make are usually labeled as experience. But with a true mistake there will be no experience gained.  :  Hades",
"Without you Eclipse cannot begin. For that sake… I regret nothing even if I have to forfeit my life  :  Arcadios",
"I was once weak I was always afraid I hidden my tears but I kept on going I kept on believing I followed my heart I found my courage and I realised if I hadn’t believed in myself then I wouldn’t have become the person I am today  :  Erza Scarlet",
"There are people in this world that enjoy being alone but there isn’t a single person that can bear solitude.  :  Makarov Dreyar",
"We don’t have to know what tomorrow holds! That’s why we can live for everything we’re worth today!  :  Natsu Dragneel",
"You don’t need a reason to cry. All you need to feel is the warmth that dwells in your chest.  :  Lucy Heartfilia",
"All living things eventually die. It’s unavoidable. But as long as you remember it will live on in your heart forever.  :  Lisanna Strauss "
"Care too little you lose them. Care too much you get hurt.  :  Gajeel Redfox", 
"It’s not about whether or not you’re a human or an Exceed. We’re all living beings and we have to do what is right. I’ll be right beside you. There’s nothing to be afraid of.  :  Wendy Marvell",
"What were you doing inside of me?! I don’t ever remember eating you!  :  Natsu Dragneel",
"It’s a hundred years too early for you to pick a fight with Mages like us.  :  Lucy Heartfilia",
"You don’t die for your friends you live for them  :  Erza Scarlet",
"Your so called “hope” is to throw the past into despair?  :  Natsu Dragneel",
"You have three choices you can give up give in or give it your all.  :  Lucy Heartfilia",
"Hurt me with the truth but never comfort me with a lie.  :  Erza Scarlet",
"Ice can even stop the time of life itself. So you’ll never be able to catch up for eternity. You’ll always be stuck there staring at the fairy tail.  :  Gray Fullbuster",
"I refuse to stand by and watch you give up. I won’t lose you I can’t. We’ll walk away from this battle together.  :  Erza Scarlet",
"It’s not a crime! Caring about your friends is not a crime!  :  Lucy Heartfilia",
"Don’t give up. It’s not over yet. Bring it on b*st*rd… I’m standing right here!  :  Natsu Dragneel",
"There’s a wall that can’t be destroyed with just power. However there is a type of power that can destroy that wall. The Power of Feelings.  :  Mavis Vermilion",
"Save the tears for when we win.  :  Natsu Dragneel",
"Feelings can be controlled but tears never lie.  :  Erza Scarlet",
"I am not going to stand here and lecture you about how to live a just and proper life… But… I will stand here and tell you to live one that has some meaning  :  Belno",
"Don’t judge me unless you have looked through my eyes experienced what I went through and cried as many tears as me. Until then back-off cause you have no idea.  :  Lucy Heartfilia",
"We’ll stop it even if my body crumbles to bits I’ll stop it with my soul!  :  Natsu Dragneel",
"If you don’t have the courage to change things then you might as well just die!!!  :  Natsu Dragneel",
"Forget what hurt you in the past but never forget what it taught you.  :  Lucy Heartfilia",
"Magic is not meant to be used to kill people… but without power we can’t protect the ones we love  :  Mirajane Strauss",
"It’s not a sin! Caring for your friends feelings is not a sin! If you disappear then Aries myself and everyone here will be filled with sadness! You won’t be repenting your sin that way!  :  Lucy Heartfilia",
"I’ll always be by your side. You’ll never be alone. You have as many hopes as there are stars that light up the sky. The wind that brushes your skin is a presentiment of tomorrow. Come lets walk in time with the song of the fairies…  :  Mavis Vermillion",
"Even if we walk on different paths one must always live on as you are able! You must never treat your own life as something insignificant! You must never forget the friends you love for as long as you live! Let bloom the flowers of light within your hearts.  :  Erza Scarlett",
"That morning’s dawn was painted a beautiful scarlet the likes of which I had never seen before. Like the color of Erza’s hair it was warm and passionate… If she could only lift her face a beautiful sky would be spread out before her.  :  Lucy Heartfilia",
"It’s not the goodbyes that hurt it’s the flashbacks that follow.  :  Gray Fullbuster",
"If you realize you made a mistake with the way you’ve been living your life you just have to take the next moment and start over.  :  Erza Scarlet",
"The fact that I’m standing here now means I’m also prepared to fight on behalf of my Guild. I don’t need your pity. Until I’ve fallen and become unable to move any longer please come at me with all your strength!  :  Wendy Marvell",
"I want to become a man who treasures his friends.  :  Rogue Cheney",
"Fear isn’t ‘evil’ it only allows us to learn our own weaknesses. When we learn our weakness people can grow stronger and kinder.  :  Gildarts Clive",
"Care too little you might lose them. Care too much you get hurt.  :  Gajeel Redfox",
"The worst kind of pain is when you’re smiling just to stop the tears from falling.  :  Lucy Heartfilia",
'We know our weakness. Now what will we do? We’ll get stronger! We’ll get up and fight!  :  Natsu Dragneel',
"None of us will ever blame our misfortunes on others… Not a single one. But… It’s okay… People all have their own reason for living. No matter how small it may be… Even you have a purpose  :  Mirajane Strauss",
'Always trying to make myself seem strong… So I locked my own heart in a suit of armor.  :  Erza Scarlet',
"No! Running away by myself? No way. It’s always more fun when we are together!  :  Lucy Heartfilia",
"Comrade isn’t simply a word. Comrades are about heart. It’s the unconditional trust in your partners. Please feel free to lean on me… and I too will lean on you as well.  :  Mavis Vermillion",
"It’s not a sin to fall in love. You can’t even arrest someone over that.  :  Gajeel Redfox",
"Remember that everyone you meet is afraid of something love something and has lost something.  :  Lucy Heartfilia",
"It’s only the end if you give up!  :  Elfman Strauss",
"Don’t give up the beginning is always the hardest so let’s keep on going till the very end.  :  Natsu Dragneel",
"If you truly desire greatness you must first know what makes you weak!  :  Erza Scarlet",
"There’s nothing happy about having your fate decided for you! You have to grab your own happiness!  :  Lucy Heartfilia",
"I don’t care if you are the strongest or top guild in Fiore but I will tell you this. You’ve made enemies of the worst possible guild to piss off.  :  Erza Scarlet",
"We are the same… It’s the same for all of us  :  Natsu Dragneel",
"Moving on doesn’t mean you forget about things. It just means you have to accept what’s happened and continue living.  :  Erza Scarlet",
"If someone here were hurt or lost their life because of me I think I would also be in pain much like Loke. But it’ll be all right. If everyone works together and unites in power we can overcome any pinch ahead right?  :  Lucy Heartfilia",
"If one really wants to change the world… they have to do it with their own hands!  :  Lucy Ashley",
"Even if I can’t see you… Even if we are separated far from each other… I’ll always be watching you. I’ll definitely watch over you forever.  :  Makarov Dreyar",
"I don’t care where I get hurt as long as my injuries are visible.  :  Gray Fullbuster",
"If it’s to protect our family be it the Kingdom or the entire world… We would make anyone our enemy! That’s what it means to be Fairy Tail!!  :  Natsu Dragneel",
"There’s no need to change the past. Because of the past we are who we are now. Every second every action from then is linked to us here and now.  :  Gray Fullbuster",
"Feelings are connection. They surpass time and find their way back to the people you love.  :  Lucy Heartfilia",
"You guys are complete idiots! I feel so sorry for you I think I’m tearing up. Phantom Lord? The spirit ruler? What a joke; I’m not afraid of you at all!  :  Lucy Heartfilia",
"In that case you have nothing to fear. Mistakes aren’t made by locking your feelings and holding back… They’re made while wearing your heart on your sleeve.  :  Mavis Vermillion",
"I won’t give up I will fight til the bitter end cause there’s no way I will back down after what you did to my friends. They are what made me the person I am today that’s why I’ll keep fighting… For my friends!  :  Lucy Heartfilia",
"The minute you think of giving up think of the reason why you held on so long.  :  Natsu Dragneel",
"Don’t feel insecure just because you lost!! We are Fairy Tail! We’re from the guild that doesn’t know when to stop! We won’t survive unless we keep running!  :  Natsu Dragneel",
"Do whatever you think is right. That’s the way of the Fairy Tale mages.  :  Makarov Dreyar",
"I wont stop fighting when im tired i’ll stop fighting when you’ve shattered my heart into a thousand pieces  :  Natsu Dragneel",
"The real sin is averting your eyes and failing to believe in anyone.  :  Natsu Dragneel",
"Manipulating the pieces according to your strategy… That is what defines a King.  :  Minerva Orland",
"It’s always sad to part with those whom you love but your companions will help you bear that sadness.  :  Erza Scarlet",
"Freedom can be found at the bottom of your heart.  :  Rob",
"If lives were lost today then lives were also born. How important each day is… depends on how important you feel it is to you.  :  Erza Scarlet",
"You never admired me… I was never a man anyone looked up to. You feared me… Let me jog your memory as to the terror I can bring  :  Gajeel Redfox",
"When we’re all alone it might be to frightening to bear… but we’re all right beside each other. We’ve got our friends close by! Now there’s nothing to fear! Because we’re not alone!!!  :  Natsu Dragneel",
"I’ll do what I want till the end. Cut me down if you want.  :  Gray Fullbuster",
"I’ll keep my promise I’ll save the world.  :  Natsu Dragneel",
"If you truly desire greatness, you must first know what makes you weak!",
"Magic is not meant to be used to kill people... but without power we can't protect the ones we love.",
"Even if I can't see you... Even if we are separated far from each other... I'll always be watching you. I'll definitely watch over you forever",
"It's only the end if you give up!",
"Do whatever you think is right. That's the way of the Fairy Tale mages.",
"Comrade isn't simply a word. Comrades are about heart. It's the unconditional trust in your partners. Please, feel free to lean on me... and I too, will lean on you as well.",
"The mistakes people make are usually labeled as experience. But with a true mistake, there will be no experience gained.",
"Freedom can be found at the bottom of your heart.",
"We'll stop it, even if my body crumbles to bits, I'll stop it with my soul!",
"There are people in this world that enjoy being alone, but there isn't a single person that can bear solitude.",
"It's always sad to part with those whom you love, but your companions will help you bear that sadness." ,
"It's not a crime! Caring about your friends is not a crime!",
"If one really wants to change the world... they have to do it with their own hands!",
"I'll do what I want till the end. Cut me down if you want.",
"In that case, you have nothing to fear. Mistakes aren't made by locking your feelings and holding back... They're made while wearing your heart on your sleeve.",
"We know our weakness. Now what will we do? We'll get stronger! We'll get up and fight!",
"If lives were lost today, then lives were also born. How important each day is... depends on how important you feel it is to you.",
"You don't need a reason to cry. All you need to feel is the warmth that dwells in your chest.",
"Care too little, you lose them. Care too much, you get hurt.",
"Moving on doesn't mean you forget about things. It just means you have to accept what's happened and continue living.",
"Save the tears for when we win.",
"I don't want to run away by myself, because no matter what, I'd rather be together with everyone",
"You don't die for your friends, you live for them",
"We’ve got our comrades right here! There’s nothing to fear! We're not alone!",
"Fear isn’t ‘evil’, it only allows us to learn our own weaknesses. When we learn our weakness, people can grow stronger and kinder.",
)